# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "grep-fu"
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Budd"]
  s.date = "2015-04-29"
  s.description = "Grep-Fu is a very fast, Rails-oriented command-line helper script for grep."
  s.email = "calamitous@calamitylane.com"
  s.executables = ["grep-fu"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/grep-fu",
    "grep-fu.gemspec",
    "lib/grep-fu.rb",
    "lib/grep-fu/find_builder.rb",
    "lib/grep-fu/options.rb",
    "spec/find_builder_spec.rb",
    "spec/grep_fu_spec.rb",
    "spec/options_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Calamitous/grep-fu"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Grep-Fu is a very fast, Rails-oriented command-line helper script for grep."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

