# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grep-fu}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Budd"]
  s.date = %q{2010-05-27}
  s.default_executable = %q{grep-fu}
  s.description = %q{Grep-Fu is a very fast, Rails-oriented command-line helper script for grep.}
  s.email = %q{calamitous@calamitylane.com}
  s.executables = ["grep-fu"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/grep-fu",
     "grep-fu.gemspec"
  ]
  s.homepage = %q{http://github.com/Calamitous/grep-fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Grep-Fu is a very fast, Rails-oriented command-line helper script for grep.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

