#!/usr/bin/env ruby

PATH_REPLACEMENTS = {
                      'a' => 'app', 
                      'c' => 'app/controllers', 
                      'h' => 'app/helpers', 
                      'm' => 'app/models', 
                      'v' => 'app/views', 
                      'l' => 'lib',
                      'p' => 'public', 
                      'css' => 'public/stylesheets', 
                      'js' => 'public/javascripts', 
                      't' => 'test',
                      's' => 'spec',
                      'vp' => 'vendor/plugins',
                      'mig' => 'db/migrate'
                    }

PRUNE_PATHS = ['/.svn', '/.git', '/vendor', '/log', '/public/yui', '/tmp', '~']
COLOR_ON_BY_DEFAULT = false
options = '-ril'

unless ARGV.size > 0
  puts "\nUsage: #{__FILE__} [findpath] search_string [--verbose]\n
    Where findpath is one of the following:
      any literal subdirectory
#{PATH_REPLACEMENTS.map { |abbr, txt| "      #{abbr} - #{txt}" }.join("\n")}\n\n"
  exit
end

clargs = ARGV
verbose = (clargs -= ['--verbose'] if clargs.include?('--verbose'))

color = (clargs -= ['--color'] if (clargs.include?('--color')) || COLOR_ON_BY_DEFAULT)
if clargs.include?('--no-color')
  color = false
  color = clargs -= [--no-color]
end

options = '-rin' if verbose
options << ' --color=always' if color

search_criteria = clargs.last
file_path = clargs.size == 2 ? PATH_REPLACEMENTS[clargs.first] || clargs.first : './'
delicious_prunes = PRUNE_PATHS ? "-path '*#{PRUNE_PATHS.join("' -prune -o -path *'")}' -prune -o" : ''

find_command = "find #{file_path} #{delicious_prunes} \\( -size -100000c -type f \\) -print0 | xargs -0 grep #{options} \"#{search_criteria}\""

if verbose
  `#{find_command}`.each_line do |found|
    file_and_line = found.slice!(/^.*?:.*?:/)
    puts "#{file_and_line}\n\t#{found.strip}"
  end
else
  puts `#{find_command}`
end

